import 'dart:math';

Random rnd = new Random();
var list = [
'I hope you sit on a wet bench and get your pants wet.',
  'May your butt itch, and your arms be to short to reach.',
  'Thy mother is so repulsive, her odor chokes the plants in her shrubbery.',
  'I would bet my hat that a wisenheimer like themself, does not wooh any attractive ladies. ',
  'I doubt any words coming from a hornswoggler like themself, could fool even a child.',
  'You absolute pigeon-livered mut.',
  'Mind your own business, muffin walloper.',
  'Your mother is a muffin walloper, and your father is a dewdropper!',
  'Leave the talking to the adults, ankle-biter.',
  'Go back to drinking your hooch, you rag-a-muffin.',
  'I bet a gal-sneaker like you never came further than doing the bear with a dame.',
  "Im quite jealous of the people who haven't met you.",
  "your mug is proof that god has a sence of humour.",
  "in the land of the witless, you would rule over all.",
  "Id prefer a battle of wits, but you appear unarmed.",
  "you sir, are the reason god created the middle finger.",
  "Sometimes I need what only you can provide, your absence.",
  "Your inferiority complex is fully justified.",
  "I've been called worse things by better people.",
  "I would agree with you, but then we would both be wrong.",
  "It is impossible to underestimate you.",
  "Isn't it rather dangerous to use one's entire vocabulary in one sentence?",
  "May I borrow your tweezers when you are done masturbating?",
  "Ahh, now that reminds me of the other day, when I was having sex with your wife.",
  "Are you always a buffoon, or is this some sort of special show for me?",
  "You seem to love nature, in spite of what it did to you.",
  "It is a shame that your parents met only once...briefly.",
  "Do not let your mind wander...it is far too small to be left alone.",
  "Your mother's breasts sag with such severity that the late, great Surrealist artist Salvador saw them and mistook them for clocks.",
  "Your rather oddly proportioned body reminds me of a humorously crafted sausage that has since gone stale.",
  "You remind me of a stork with a lacerated colon.",
  "You have all of the virtues I dislike and none of the vices I admire.",
  "As a baby, did you have to get your mother drunk just so you could breast-feed?",
  "You are beautiful where it counts most. On the inside.",
  "You would be out of your depth in a puddle.",
  "Save your breath.  You'll need it for your blow-up doll.",
  "My good man, I don't know what makes you so stupid.  But whatever it is, it's really working.",
  "I would love to see it from your perspective, but I am incapable of sticking my head that far up my own ass.",
  "I wish you dripped out your mothers sauce-box when you were conceived.",
  "I respectfully, don't care.",

];
