var list = [
'I hope you sit on a wet bench and get your pants wet.',
  'May your butt itch, and your arms be to short to reach.',
'Thy mother is so repulsive, her odor chokes the plants in her shrubbery.',
'I would bet my hat that a wisenheimer like themself, does not wooh any attractive ladies. ',
'I doubt any words coming from a hornswoggler like themself, could fool even a child.',
'You absolute pigeon-livered mut.',
'Mind your own business, muffin walloper.',
'Your mother is a muffin walloper, and your father is a dewdropper!',
'Leave the talking to the adults, ankle-biter.',
'Go back to drinking your hooch, you rag-a-muffin.',
'I bet a gal-sneaker like you never came further than doing the bear with a dame.',
"Im quite jealous of the people who haven't met you.",
"your mug is proof that god has a sence of humour.",
"in the land of the witless, you would rule over all.",
"Id prefer a battle of wits, but you appear unarmed.",
"you sir, are the reason god created the middle finger.",
"Sometimes I need what only you can provide, your absence.",
"Your inferiority complex is fully justified.",
"I've been called worse things by better people.",
"I would agree with you, but then we would both be wrong.",
"It is impossible to underestimate you.",
"Isn't it rather dangerous to use one's entire vocabulary in one sentence?",
"May I borrow your tweezers when you are done masturbating?",
"Ahh, now that reminds me of the other day, when I was having sex with your wife.",
"Are you always a buffoon, or is this some sort of special show for me?",
"You seem to love nature, in spite of what it did to you.",
"It is a shame that your parents met only once...briefly.",
"Do not let your mind wander...it is far too small to be left alone.",
"Your mother's breasts sag with such severity that the late, great Surrealist artist Salvador saw them and mistook them for clocks.",
"Your rather oddly proportioned body reminds me of a humorously crafted sausage that has since gone stale.",
"You remind me of a stork with a lacerated colon.",
"You have all of the virtues I dislike and none of the vices I admire.",
"As a baby, did you have to get your mother drunk just so you could breast-feed?",
"You are beautiful where it counts most. On the inside.",
"You would be out of your depth in a puddle.",
"Save your breath.  You'll need it for your blow-up doll.",
"My good man, I don't know what makes you so stupid.  But whatever it is, it's really working.",
"I would love to see it from your perspective, but I am incapable of sticking my head that far up my own ass.",
"I wish you dripped out your mothers sauce-box when you were conceived.",
"I respectfully, don't care.",
  "You are about as useful as a knitted condom.",
  "I'd slap you, but that'd be animal abuse.",
  "Off is the general direction in which I wish you would fuck.",
  "I'll do my best to be more kind, If you do your best being smarter.",
  "You resemble something I drew with my left hand.",
  "If laughter is the best medicine, your face must be curing the world.",
  "Hey, train wreck, this isn't your station.",
  "You're not completely useless, you could be used as a bad example.",
  "You look like a before picture.",
  "You are the reason tubes of toothpaste comes with instructions.",
  "If I wanted to end my life, I would climb up to your ego, and jump down to your IQ level.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Life is full of disappointments, and I just added you to the list.",
  "You remind me of a penny. Two-faced, and low valued.",
  "The village called. They'd like their idiot back. You better get going.",
  "You have the right to remain silent, because whatever you say will probably be stupid anyway.",
  "Your family tree must be a cactus, because your all a bunch of pricks.",
  "I was going to give you a nasty look, but I see that you already got one.",
  "You're about as useful as an ashtray on a motorcycle.",
  "I believed in evolution until i met you.",
  "If I threw a stick, you'd leave, right?",
  "You'll never be the man your mom is.",
  "You have your entire life to be a buffoon. Why not take today off?",
  "Some day you'll go far, and I hope you stay there.",
  "May the chocolate chips in your cookies always turn out to be raisins.",
  "May every sock you wear be slighty rotated, just enough for it to be uncomfortable.",
  "May both sides of your pillow be warm.",
  "I don't know that your problem is, but I'm guessing you have a hard time pronouncing it.",
  "Everyone's entitled to act stupid once in awhile, but you clearly abuse the privilege.",
  "I was today years old when I realized I didn’t like you.",
  "Oops, my bad. I could’ve sworn I was dealing with an adult.",
  "I love what you’ve done with your hair. How do you get it to come out of your nostrils like that?",
  "I’m busy right now, can I ignore you another time?",
  "You’re a gray sprinkle on a rainbow cupcake.",
  "You bring everyone so much joy! You know, when you leave the room. But, still.",
  "I hope your wife brings a date to your funeral.",
  "Keep rolling your eyes, you might eventually find a brain.",
  "Your face makes onions cry.",
  "You have so many gaps in your teeth it looks like your tongue is in jail.",
  "I’ll never forget the first time we met. But I’ll keep trying.",
  "Oh, I’m sorry. Did the middle of my sentence interrupt the beginning of yours?",
  "Hold still. I’m trying to imagine you with personality.",
  "I’m not insulting you, I’m describing you.",
  "You are the human version of period cramps.",
  "I’m an acquired taste. If you don’t like me, acquire some taste.",
  "Don’t worry, the first 40 years of childhood are always the hardest.",
  "If you’re going to be two-faced, at least make one of them pretty.",
  "If you have a problem with me, write the problem on a piece of paper, fold it, and shove it up your ass.",
  "I thought of you today. It reminded me to take out the trash.",
  "Beauty is only skin deep, but ugly goes clean to the bone.",
  "I’d rather treat my baby’s diaper rash than have lunch with you.",
  "When you look in the mirror, say hi to the clown you see in there for me, would you?",
  "Somewhere out there is a tree tirelessly producing oxygen for you. You owe it an apology.",
  "If I had a face like yours, I would sue my parents.",
  "You must have been born on a highway. That’s where most accidents happen.",
  "You’re the reason the gene pool needs a lifeguard.",
  "I’m glad to see you’re not letting education get in the way of your ignorance.",
  "Your only chance of getting laid is to crawl up a chicken butt and wait.",
  "Don’t be ashamed of who you are. That’s your parent’s job.",
  "If you were an inanimate object, you’d be a participation trophy.",
  "Unless your name is Google, stop acting like you know everything!",
  "Yeah? Well, you smell like hot dog water.",
  "First off: Brush your teeth.",
  "I don’t have the patience or the crayons to explain this to you.",
  "I bet your parents change the subject when their friends ask about you.",
  "You should carry a plant around with you to replace the oxygen you waste.",
  "If you were the light at the end of the tunnel, I’d turn back around.",
  "Were you born this stupid or did you take lessons?",
  "You should really come with a warning label.",
  "If I wanted to hear from an asshole, I’d fart.",
  "Too bad you can’t Photoshop your ugly personality.",
  "The people who tolerate you on a daily basis are the real heroes.",
  "Please just tell me you don’t plan to home-school your kids.",
  "If you’re going to act like a turd, go lay on the yard.",
  "If ignorance is bliss, you must be the happiest person on the planet.",
  "Good story, but in what chapter do you shut up?",
  "I am returning your nose. I found it in my business.",
  "Jealousy is a disease. Get well soon.",
  "I could eat a bowl of alphabet soup and poop out a smarter statement than whatever you just said.",
  "Your only purpose in life is to become an organ donor.",
  "There are some remarkably dumb people in this world. Thanks for helping me understand that.",
  "The last time I saw a face like yours, I fed it a banana.",
  "As an outsider, what do you think of the human race?",
  "Don’t feel bad. A lot of people have no talent.",
  "Did your parents ever ask you to run away from home?",
  "I have seen people like you. But I had to pay admission.",
  "Two wrongs don’t make a right. Take your parents, for instance.",
  "One day, I hope you’ll choke on the crap you talk.",
  "If I said anything to offend you it was purely intentional.",
  "I hope your next blowjob is from a shark.",
  "You look like something that came out of a slow cooker.",
  "I was going to make a joke about your life, but I see life beat me to the punch.",
  "I treasure the time I don’t spend with you.",
  "You clinking, clanking, clattering collection of caliginous junk!",
  "You're about as much use as a condom machine in the Vatican.",
  "Your mother was a hamster and your father smelt of elderberries.",
  "I fart in your general direction.",
  "You are a sad strange little man, and you have my pity.",
  "I would tell you to go fuck yourself but I’m pretty sure you’d be disappointed.",
  "This is why people talk about you.",
  "You are so ugly that when your mother dropped you off at school, she got a ticket for littering.",
  "You've only got 2 brain cells and they are both fighting for 3rd place.",
  "I bet your mom doesn’t put your drawings on the fridge.",
  "If I gave you a penny for your thoughts, I'd get change.",
  "If you had one more brain cell, it would be lonely.",
  "Light travels faster than sound. This is why some people appear bright until you hear them speak.",
  "Anybody who told you to just be yourself couldn't have given you worse advice.",
  "If you have something to say, raise your hand and place it over your mouth.",
  "I haven't seen you run that fast since Twinkies went on sale.",
  "Do you want people to accept you as you are or do you want them to like you?",
  "Mirrors can't talk. Luckily for you, they can't laugh either.",
  "You were so ugly when you were born that the doctor put tinted windows on your incubator.",
  "Your face looks like you've been using it as a doorstop.",
  "Did the mental hospital test too many drugs on you today?",
  "It's hard to get the big picture when you have such a small screen.",
  "If you can't laugh at yourself, I'd be glad to do so for you.",
  "In order for you to insult me, I would first have to value your opinion.",
  "People like you should use a glue stick instead of chapstick.",
  "Your father should have wiped you on the sheets.",
  "I wonder if you'd be able to speak more clearly if your parents were second cousins instead of first.",
  "Who sprinkled the bitchy dust?",
  "I didn't know you spoke shit so fluently.",
  "ABRACADABRA! Nope. You're still a bitch.",
  "Wipe your mouth. There is still a tiny bit of bullshit around your libs.",
  "Your gene pool could use a little chlorine.",
  "You have something on your chin… No, the 3rd one down.",
  "Aha! I see the fuck-up fairy has visited us again!",
  "When God put teeth in your mouth, he ruined a perfectly good arsehole.",
  "If you were any less intelligent I'd have to water you twice a week.",
  "You're more useless than Anne Frank's drumset.",
  "You look like your face was on fire, and someone tried to put it out with a fork.",
  "Anyone ever tell you you look like a penis with a little hat on?",
  "If your brain exploded, it wouldn't even mess up your hair.",
  "Your parents wouldn't happen to be siblings, would they?",
  "Your family tree doesn't branch much, does it?",
  "I hope you outlive your kids.",
  "You're a perfect reason for being Pro-choice.",
  "You're an inspiration for birth control.",
  "The best part of you dripped down your mother's leg.",
  "Your ambition outweighs your relevant skills",
  "You're educated beyond your intelligence.",
  "I'd slap you but i don't want to get slut on my hand.",
  "I'd call you a cunt, but you lack the warmth and the depth.",
  "The sound of your piss hitting the urinal is feminine.",
  "I hope you step on a Lego.",
  "I hope your asshole grows taste buds.",
  "If your vagina had a password, it would be 'Password'.",
  "If you die, I will not be attending your funeral.",
  "Your mother has two cunts, and one of them is you.",
  "You're not pretty enough to be this much of a bitch.",
  "Your mother fucks for bricks, so she can build your sister a whore house.",
  "You are not very nice, and I don't like you.",
  "I hope someone you love catches on fire.",
];

